CREATE TABLE CDW_UAS_D_STUDENT_EFF_DATE (
STUD_ID NUMBER(10) PRIMARY KEY,
STUD_F_NAME VARCHAR2(40),
STUD_M_NAME VARCHAR2(40),
STUD_L_NAME VARCHAR2(40),
STUD_ROLLNO NUMBER(9),
STUD_STREET VARCHAR2(38),
STUD_CITY VARCHAR2(30),
STUD_STATE VARCHAR2(30),
STUD_COUNTRY VARCHAR2(30),
STUD_ZIP NUMBER(7),
STUD_PHONE VARCHAR2(12),
STUD_EMAIL VARCHAR2(40),
CREATED_DATE TIMESTAMP(0),
END_DATE DATE
);

DROP TABLE CDW_UAS_D_STUDENT_EFF_DATE;
rollback;
truncate table CDW_UAS_D_STUDENT_EFF_DATE;

select * from CDW_UAS_D_STUDENT_EFF_DATE;


CREATE TABLE CDW_UAS_D_COLLEGE(
COLLEGE_CODE NUMBER(9) PRIMARY KEY NOT NULL,
COLLEGE_NAME VARCHAR2(25) NOT NULL,
COLLEGE_STREET VARCHAR2(30) NOT NULL,
COLLEGE_CITY VARCHAR(30) NOT NULL,
COLLEGE_STATE VARCHAR(30) NOT NULL,
COLLEGE_ZIP NUMBER(7) NULL,
COLLEGE_PHONE VARCHAR2(13) NOT NULL
);
DROP TABLE CDW_UAS_D_COLLEGE;

TRUNCATE TABLE CDW_UAS_D_COLLEGE;

select * from CDW_UAS_D_COLLEGE;

CREATE TABLE CDW_UAS_D_FACULTY(
FACULTY_CODE NUMBER(9)PRIMARY KEY NOT NULL,
FACULTY_NAME VARCHAR2(25) NOT NULL,
FACULTY_DESIGNATION VARCHAR2(30) NOT NULL,
FACULTY_QUALIFICATION VARCHAR2(30) NOT NULL);

DROP TABLE CDW_UAS_D_FACULTY;
rollback;
TRUNCATE TABLE CDW_UAS_D_FACULTY;

select * from CDW_UAS_D_FACULTY;

CREATE TABLE CDW_UAS_D_DEPARTMENT(
DEPARTMENT_ID NUMBER(10) PRIMARY KEY NOT NULL,
DEPARTMENT_NAME VARCHAR2(50) NOT NULL,
DEPARTMENT_NO NUMBER(9) NOT NULL,
DEPARTMENT_PHONE VARCHAR2(12) NOT NULL,
DEPARTMENT_HEAD VARCHAR2(30) NOT NULL);

DROP TABLE CDW_UAS_D_DEPARTMENT;
TRUNCATE TABLE CDW_UAS_D_DEPARTMENT;

select * from CDW_UAS_D_DEPARTMENT;

CREATE TABLE CDW_SAPP_D_COURSE(
COURSE_CODE NUMBER(10) PRIMARY KEY NOT NULL,
COURSE_NAME VARCHAR2(30) NOT NULL,
DEPARTMENT_ID NUMBER(10) NOT NULL,
MARK_REQ VARCHAR2(9) NOT NULL
);

DROP TABLE CDW_SAPP_D_COURSE;

TRUNCATE TABLE CDW_SAPP_D_COURSE;

select * from CDW_SAPP_D_COURSE;

--CREATE TABLE CDW_UAS_D_TIME(
--TIME_ID VARCHAR2(8),
--DAY NUMBER(2),
--MONTH NUMBER(2),
--QUARTER VARCHAR2(28),
--YEAR NUMBER(4));
--
--DROP TABLE  CDW_UAS_D_TIME;


CREATE TABLE CDW_UAS_STG_RESULT(
CDW_P_RESULT_DSET_KEY NUMBER(9) primary key NOT NULL,
RESULT_F_Student_KEY NUMBER(10) NOT NULL,
RESULT_F_DEPARTMENT_KEY NUMBER(10)NOT NULL,
RESULT_F_COLLEGE_CODE NUMBER(9) NOT NULL,
RESULT_F_COLLEGE_NAME VARCHAR(25)NOT NULL,
RESULT_F_COURSE_CODE NUMBER(10) NOT NULL,
RESULT_F_COURSE_NAME VARCHAR(30) NOT NULL,
RESULT_F_FACULTY_NO NUMBER(10),
RESULT_MARKS NUMBER(7),
RESULT_GRADE VARCHAR(10),
CREATED_DATE TIMESTAMP(0),
CREATED_BY VARCHAR(40));

DROP TABLE CDW_UAS_STG_RESULT;

truncate table CDW_UAS_STG_RESULT;

select * from CDW_UAS_STG_RESULT;


CREATE TABLE CDW_UAS_F_RESULT(
CDW_XYZ_F_RESULT_DSET_KEY NUMBER(9) PRIMARY KEY NOT NULL,
RESULT_F_STUDENT_KEY NUMBER(10) NOT NULL,
RESULT_F_DEPARTMENT_KEY NUMBER(10) NOT NULL,
RESULT_F_COLLEGE_CODE NUMBER(9) NOT NULL,
RESULT_F_COLLEGE_NAME VARCHAR2(25) NOT NULL,
RESULT_F_COURSE_CODE NUMBER(10) NOT NULL,
RESULT_F_COURSE_NAME VARCHAR2(30) NOT NULL,
RESULT_MARKS NUMBER(7) NOT NULL,
RESULT_GRADE VARCHAR2(10) NOT NULL,
CREATED_DATE TIMESTAMP(0),
CREATED_BY VARCHAR(40)
);
DROP TABLE CDW_UAS_F_RESULT;
TRUNCATE TABLE CDW_UAS_F_RESULT;
SELECT * FROM CDW_UAS_F_RESULT;

CREATE TABLE CDW_UAS_F_AGG_DATA(
CDW_RESULT_AGG_DSET_KEY NUMBER(9) PRIMARY KEY NOT NULL,
COLLEGE_CODE NUMBER(9) NOT NULL,
COLLEGE_NAME VARCHAR2(25) NOT NULL,
COURSE_CODE NUMBER(10) NOT NULL,
COURSE_NAME VARCHAR2(30) NOT NULL,
TOTAL_PASS NUMBER(7)NOT NULL,
MAXIMUM_MARK NUMBER(8,2) NOT NULL,
CREATED_DATE DATE NOT NULL
);

DROP TABLE CDW_UAS_F_AGG_DATA;

TRUNCATE TABLE CDW_UAS_F_AGG_DATA;

SELECT * FROM CDW_UAS_F_AGG_DATA;